export const PHOTOGRAPH_CREATE = 'PHOTOGRAPH_CREATE';
export const PHOTOGRAPHS_GET = 'PHOTOGRAPHS_GET';
export const PHOTOGRAPH_GET = 'PHOTOGRAPH_GET';
export const PHOTOGRAPH_CLEAR = 'PHOTOGRAPH_CLEAR';
export const PHOTOGRAPH_UPDATE = 'PHOTOGRAPH_UPDATE';
